#!/bin/bash
#===============================================================================
#
#         FILE:  nllc_pf
#
#        USAGE:  ./arxiv_pf 
#
#  DESCRIPTION:  An alternate development server to bring up Catalyst 
#
#===============================================================================

CATALYST_ENGINE='HTTP::Prefork' script/nllc_server.pl -p 8123 -k 

